"""The PROPOSED-RIG URDF stays the shadow of the code that defines the rig.

`assets/proposed_rig/*.urdf` is generated by `scripts/gen_proposed_rig_urdf.py`
from `layout.FLEET_PROPOSED` / `mounts.MOUNTS` / `frames`, so it is only ever
as true as the last regeneration.  These tests are what makes that a fact
instead of a habit:

  * regeneration is deterministic and byte-identical to what is committed;
  * the six welds ARE `fleet.rig("proposed")`'s base transforms;
  * the joint limits are FR3's, not the vendored Panda's;
  * an INDEPENDENT forward kinematics — walked over the URDF's own XML, no
    drake, no frames.py — puts every pen tip where `frames` puts it.

The pydrake load lives in `scripts/check_proposed_rig_urdf.py` (station venv);
the system python has no drake, so the FK cross-check here re-derives the
chain from the file instead, which is the stronger test of the two anyway.

`frames.PEN_LAT` is a process GLOBAL and mutating it leaks into every other
test: nothing here touches it, and one test pins that.

Run: pytest tests/test_proposed_rig_urdf.py
"""
import importlib.util
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import numpy as np
import pytest

ROOT = Path(__file__).parents[1]
sys.path.insert(0, str(ROOT))

from aris_sixarm import fleet, frames, mounts, rig_final  # noqa: E402
from aris_sixarm.frames import (D_HAND_TCP, FR3_MAX, FR3_MIN,  # noqa: E402
                                PEN_EXT_HOLDER, PEN_LAT_HOLDER, QD_MAX, TAU_MAX,
                                fk, tool_offset)
from aris_sixarm.layout import FLEET_PROPOSED, LAYOUT_PROPOSED  # noqa: E402
from aris_sixarm.rig_final6 import SHEET_FINAL6  # noqa: E402

URDF_DIR = ROOT / "assets/proposed_rig"
INSTALLATION = URDF_DIR / "installation.urdf"
ENVIRONMENT = URDF_DIR / "environment.urdf"
H_INV = float(LAYOUT_PROPOSED["h"])
DRAKE_NS = "{http://drake.mit.edu}"


def _gen_module():
    """`scripts/gen_proposed_rig_urdf.py` as a module (scripts is not a
    package, and the generator is the thing under test)."""
    spec = importlib.util.spec_from_file_location(
        "gen_proposed_rig_urdf", ROOT / "scripts/gen_proposed_rig_urdf.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


@pytest.fixture(scope="module")
def root():
    return ET.parse(INSTALLATION).getroot()


@pytest.fixture(scope="module")
def links(root):
    return {lk.get("name"): lk for lk in root.findall("link")}


@pytest.fixture(scope="module")
def joints(root):
    return {j.get("name"): j for j in root.findall("joint")}


# ==========================================================================
# the file is a build product, and it rebuilds to itself
# ==========================================================================
def test_regeneration_is_byte_stable(tmp_path):
    gen = _gen_module()
    gen.OUT_DIR = tmp_path
    gen.main()
    gen.main()                                   # twice: no clock, no rng
    for name in ("installation.urdf", "environment.urdf"):
        assert (tmp_path / name).read_bytes() == (URDF_DIR / name).read_bytes(), \
            f"{name} is stale — run scripts/gen_proposed_rig_urdf.py"


def test_the_urdf_is_the_rig_ARIS_RIG_proposed_activates():
    # `fleet.rig` is the door every script goes through; the generator reads
    # `layout.FLEET_PROPOSED` directly.  They must be the same object, or the
    # URDF is a picture of a rig nobody runs.
    fl, sheet = fleet.rig("proposed")
    assert fl is FLEET_PROPOSED
    assert tuple(sheet) == tuple(SHEET_FINAL6)
    assert len(fl) == 6 and all(s.mount == "inv" for s in fl.values())


def test_pen_lat_global_is_not_touched_by_importing_the_generator():
    before = frames.PEN_LAT
    _gen_module()
    assert frames.PEN_LAT == before == 0.0


# ==========================================================================
# the six welds are the fleet's base transforms
# ==========================================================================
def _rpy(r, p, y):
    return frames.rotz(y) @ frames.roty(p) @ frames.rotx(r)


def _origin_of(el):
    """(4,4) from a URDF <origin> child (missing -> identity)."""
    o = el.find("origin")
    xyz = [0.0, 0.0, 0.0]
    rpy = [0.0, 0.0, 0.0]
    if o is not None:
        if o.get("xyz"):
            xyz = [float(v) for v in o.get("xyz").split()]
        if o.get("rpy"):
            rpy = [float(v) for v in o.get("rpy").split()]
    T = np.eye(4)
    T[:3, :3] = _rpy(*rpy)
    T[:3, 3] = xyz
    return T


def test_base_poses_match_fleet_proposed(joints):
    for aid, spec in FLEET_PROPOSED.items():
        j = joints[f"arm{aid}_mount_weld"]
        assert j.get("type") == "fixed"
        assert j.find("parent").get("link") == "world"
        assert j.find("child").get("link") == f"arm{aid}_panda_link0"
        assert np.allclose(_origin_of(j), spec.T_world_base(H_INV), atol=1e-9)


def test_the_bases_are_the_regular_2x3_grid(joints):
    P = np.array([_origin_of(joints[f"arm{a}_mount_weld"])[:3, 3]
                  for a in FLEET_PROPOSED])
    assert np.allclose(P[:, 2], H_INV)                 # one ceiling grid
    W, H = SHEET_FINAL6
    assert sorted(set(np.round(P[:, 0], 9))) == \
        sorted(np.round([W / 2 - 0.61 / 2, W / 2 + 0.61 / 2], 9))
    assert sorted(set(np.round(P[:, 1], 9))) == \
        sorted(np.round([H / 6, H / 2, 5 * H / 6], 9))
    # every base is OVER the paper: that is the whole reason 0+6 beat 2+4
    assert np.all((P[:, 0] > 0) & (P[:, 0] < W))
    assert np.all((P[:, 1] > 0) & (P[:, 1] < H))


def test_every_arm_hangs(joints):
    for aid in FLEET_PROPOSED:
        R = _origin_of(joints[f"arm{aid}_mount_weld"])[:3, :3]
        assert np.allclose(R[:, 2], [0, 0, -1], atol=1e-9)   # J1 axis DOWN


# ==========================================================================
# FR3, not Panda
# ==========================================================================
def test_joint_limits_are_fr3(joints):
    panda = ET.parse(ROOT / "assets/franka_description/urdf/panda_arm_hand.urdf"
                     ).getroot()
    vendor = {j.get("name"): j.find("limit") for j in panda.findall("joint")
              if j.find("limit") is not None}
    for aid in FLEET_PROPOSED:
        for i in range(7):
            lim = joints[f"arm{aid}_panda_joint{i + 1}"].find("limit")
            assert float(lim.get("lower")) == pytest.approx(FR3_MIN[i], abs=1e-9)
            assert float(lim.get("upper")) == pytest.approx(FR3_MAX[i], abs=1e-9)
            assert float(lim.get("velocity")) == pytest.approx(QD_MAX[i], abs=1e-9)
            assert float(lim.get("effort")) == pytest.approx(TAU_MAX[i], abs=1e-9)
            # the Panda acceleration hint is a different robot's number
            assert f"{DRAKE_NS}acceleration" not in lim.attrib
    # and the point of all that: they are NOT what the vendored file says
    v = vendor["panda_joint1"]
    assert float(v.get("lower")) != pytest.approx(FR3_MIN[0])
    assert float(v.get("velocity")) != pytest.approx(QD_MAX[0])


def test_fingers_are_fixed_and_there_are_42_dof(root, joints):
    rev = [j for j in root.findall("joint") if j.get("type") == "revolute"]
    assert len(rev) == 7 * len(FLEET_PROPOSED)
    for aid in FLEET_PROPOSED:
        for k in (1, 2):
            j = joints[f"arm{aid}_panda_finger_joint{k}"]
            assert j.get("type") == "fixed" and j.find("limit") is None
            y = float(j.find("origin").get("xyz").split()[1])
            assert abs(y) == pytest.approx(0.0285, abs=1e-9)


# ==========================================================================
# THE CROSS-CHECK: FK walked over the URDF's own XML vs frames.py
# ==========================================================================
def urdf_link_poses(root, q_by_joint):
    """Walk the URDF tree from `world` -> {link: (4,4) world pose}.

    Deliberately independent of everything else in the repo: this reads the
    file, nothing else, so agreement with `frames.fk` is evidence about the
    file rather than about a shared helper.
    """
    js = []
    for j in root.findall("joint"):
        ax = j.find("axis")
        js.append(dict(name=j.get("name"), type=j.get("type"),
                       parent=j.find("parent").get("link"),
                       child=j.find("child").get("link"), T=_origin_of(j),
                       axis=np.array([float(v) for v in ax.get("xyz").split()]
                                     if ax is not None else [0, 0, 1.0])))
    out = {"world": np.eye(4)}
    pending = list(js)
    while pending:
        moved = False
        for j in list(pending):
            if j["parent"] not in out:
                continue
            T = out[j["parent"]] @ j["T"]
            if j["type"] == "revolute":
                Tq = np.eye(4)
                Tq[:3, :3] = frames.rot_axis(j["axis"],
                                             q_by_joint.get(j["name"], 0.0))
                T = T @ Tq
            elif j["type"] != "fixed":
                raise AssertionError(f"unexpected joint type {j['type']}")
            out[j["child"]] = T
            pending.remove(j)
            moved = True
        assert moved, f"URDF chain is not connected to world: {pending[:3]}"
    return out


def _sample_qs(n=16, seed=20260825):
    rng = np.random.default_rng(seed)
    qs = [np.asarray(next(iter(FLEET_PROPOSED.values())).q_seed, float)]
    qs += list(rng.uniform(FR3_MIN + 0.10, FR3_MAX - 0.10, size=(n, 7)))
    return qs


def test_pen_tip_fk_matches_frames(root):
    """The URDF's pen_tip == frames FK + the fleet base transform.

    `pen_lat` is passed EXPLICITLY (the module global stays inline); this is
    the lateral holder, which is what the proposed rig carries.
    """
    off = tool_offset(PEN_EXT_HOLDER, PEN_LAT_HOLDER)
    worst = 0.0
    for q in _sample_qs():
        qmap = {f"arm{a}_panda_joint{i + 1}": q[i]
                for a in FLEET_PROPOSED for i in range(7)}
        poses = urdf_link_poses(root, qmap)
        T_b, _ = fk(q)                       # hand TCP in link0, frames DH
        for aid, spec in FLEET_PROPOSED.items():
            Twb = spec.T_world_base(H_INV)
            p_want = Twb[:3, :3] @ (T_b[:3, 3] + T_b[:3, :3] @ off) + Twb[:3, 3]
            R_want = Twb[:3, :3] @ T_b[:3, :3]
            T_got = poses[f"arm{aid}_pen_tip"]
            worst = max(worst, float(np.max(np.abs(T_got[:3, 3] - p_want))))
            assert np.allclose(T_got[:3, 3], p_want, atol=1e-8), (aid, q)
            assert np.allclose(T_got[:3, :3], R_want, atol=1e-8), (aid, q)
    assert worst < 1e-8, worst


def test_the_tool_chain_is_the_lateral_holder(root, links, joints):
    """bracket `PEN_LAT_HOLDER` along hand x, then `PEN_EXT_HOLDER` down to
    the tip — and the TCP frame sits where `frames.TCP_D` says it does.

    Both were 0.110 until 2026-09-03, when the photo of the real gripper put
    the tip ~5 cm below the Fat blades' plates (frames.py).  The pair is
    USER-SPECIFIED, never gate-validated; only the INLINE pen's 0.110 was."""
    for aid in FLEET_PROPOSED:
        p = f"arm{aid}_"
        assert joints[f"{p}tcp_weld"].find("parent").get("link") == \
            f"{p}panda_hand"
        assert np.allclose(_origin_of(joints[f"{p}tcp_weld"])[:3, 3],
                           [0, 0, D_HAND_TCP], atol=1e-9)
        assert np.allclose(_origin_of(joints[f"{p}pen_body_weld"])[:3, 3],
                           [PEN_LAT_HOLDER, 0, 0], atol=1e-9)
        assert np.allclose(_origin_of(joints[f"{p}pen_tip_weld"])[:3, 3],
                           [0, 0, PEN_EXT_HOLDER], atol=1e-9)
        # `pen_bracket` / `pen_body` are STATIC_CAPSULES_LAT written out — the
        # L-shaped envelope the study gated every pose against.  They are
        # COLLISION-ONLY: the real holder is not an L, and drawing one would
        # be a lie, but a checker still gets what the planner certified.
        for name, r, L in ((f"{p}pen_bracket", rig_final.BRACKET_R_LAT,
                            PEN_LAT_HOLDER),
                           (f"{p}pen_body", rig_final.PEN_R_LAT, PEN_EXT_HOLDER)):
            assert links[name].find("visual") is None, name
            cyl = links[name].find("collision/geometry/cylinder")
            assert float(cyl.get("radius")) == pytest.approx(r, abs=1e-9)
            assert float(cyl.get("length")) == pytest.approx(L, abs=1e-9)
        # the tip is a FRAME: a marker, never an obstacle
        assert links[f"{p}pen_tip"].find("collision") is None


# ==========================================================================
# the 22-deg CAD holder (2026-08-19 delivery, no assembly file)
# ==========================================================================
def test_the_cad_holder_is_the_visual_and_rides_the_hand(links, joints):
    P = rig_final.PENHOLDER22
    for aid in FLEET_PROPOSED:
        p = f"arm{aid}_"
        j = joints[f"{p}pen_holder_weld"]
        assert j.find("parent").get("link") == f"{p}{P['parent']}"
        # the meshes are baked in the hand frame: the weld must be identity
        assert np.allclose(_origin_of(j), np.eye(4), atol=1e-12)
        vis = links[f"{p}pen_holder"].findall("visual")
        assert [v.find("geometry/mesh").get("filename") for v in vis] == \
            list(P["visual_meshes"])
        for v in vis:                       # baked => no per-visual placement
            assert np.allclose(_origin_of(v), np.eye(4), atol=1e-12)
        # ... and distinct material names, or a URDF reader picks one colour
        names = [v.find("material").get("name") for v in vis]
        assert len(set(names)) == len(names)


def test_the_committed_holder_meshes_exist_and_are_within_budget():
    for mesh in rig_final.PENHOLDER22["visual_meshes"]:
        f = URDF_DIR / mesh
        assert f.is_file(), f"run scripts/extract_penholder22_meshes.py"
        n = sum(1 for line in f.read_text().splitlines()
                if line.startswith("f "))
        assert 500 < n <= 8000, f"{mesh}: {n} faces is off the repo's budget"


def test_the_holder_collision_envelope_is_the_shared_one(links):
    """The URDF's collision primitives ARE `penholder22_collision` — one
    source, four cylinders coaxial with the bore (three for the housing and
    cap, one for the pencil tail), radii measured not fitted by eye."""
    want = rig_final.penholder22_collision(PEN_EXT_HOLDER, PEN_LAT_HOLDER, D_HAND_TCP)
    for aid in FLEET_PROPOSED:
        cols = links[f"arm{aid}_pen_holder"].findall("collision")
        assert len(cols) == len(want) == 4
        for c, (kind, T, par) in zip(cols, want):
            assert kind == "cylinder"
            assert np.allclose(_origin_of(c), T, atol=1e-9)
            cyl = c.find("geometry/cylinder")
            assert float(cyl.get("radius")) == pytest.approx(par[0], abs=1e-9)
            assert float(cyl.get("length")) == pytest.approx(par[1], abs=1e-9)


def test_the_holder_envelope_encloses_the_committed_meshes():
    """CONSERVATISM.  Rule for a collision proxy: it may be fat, it may not be
    thin.  Every vertex of both committed meshes is inside the union."""
    trimesh = pytest.importorskip("trimesh")
    # the HOUSING's own three, not the tail's fourth: a hull that was not
    # fitted to these meshes has no business rescuing a vertex of them
    prims = rig_final.penholder22_collision(PEN_EXT_HOLDER, PEN_LAT_HOLDER,
                                            D_HAND_TCP)[:3]
    for mesh in rig_final.PENHOLDER22["visual_meshes"]:
        V = np.asarray(trimesh.load(URDF_DIR / mesh, force="mesh").vertices)
        worst = np.full(len(V), np.inf)
        for _, T, (r, L) in prims:
            q = (V - T[:3, 3]) @ T[:3, :3]
            worst = np.minimum(worst, np.maximum(
                np.linalg.norm(q[:, :2], axis=1) - r, np.abs(q[:, 2]) - L / 2))
        assert worst.max() <= 1e-9, f"{mesh}: {worst.max() * 1000:.3f} mm out"


def test_the_holder_placement_aims_at_the_planning_tip():
    """The delivery has no assembly file, so the placement is INFERRED — but
    it is inferred to satisfy the gate-validated tool transform, and that is
    checkable: the bore points along the TCP->tip ray, the mount post's axis
    is the finger-travel axis, and the grip centre is the TCP.

    THE SENSE IS PART OF THE CLAIM.  This asserted `[-1, 0, 0]` until
    2026-09-03, which is the housing mounted END-FOR-END: an axis-only check
    passes either way round, which is how the error survived.  The pen leaves
    through the CAP — the 10-deg assembly puts its spring at the end away from
    the cap, its pencil 17.000 mm proud of the cap and 72.514 mm proud of the
    tail face, and its preview draws exactly that — so +X_housing points at
    the tip.  docs/SYSTEM_MODEL.md 7c.

    THE BORE IS THE GRIP -> TIP RAY.  It was the TCP -> tip ray while the grip
    sat on the TCP; on 2026-09-04 the photo of the real gripper put the holder
    at the FAR END of the Fat finger plates ("the tip of the finger
    extension"), so the grip is 66.5 mm out along hand x
    (`PENHOLDER22["grip_hand_x"]`) and the two rays are 20 deg apart — 45.00
    for the bore, 64.85 for the TCP ray.  docs/SYSTEM_MODEL.md 7e.
    """
    GX = rig_final.PENHOLDER22["grip_hand_x"]
    T_h, T_c, exit_x, reach = rig_final.penholder22_T_hand(
        PEN_EXT_HOLDER, PEN_LAT_HOLDER, D_HAND_TCP)
    u = np.array([PEN_LAT_HOLDER - GX, 0.0, PEN_EXT_HOLDER])
    u = u / np.linalg.norm(u)
    assert np.allclose(T_h[:3, :3] @ [1, 0, 0], u, atol=1e-12)    # bore
    assert np.allclose(T_h[:3, :3] @ [0, 0, 1], [0, 1, 0], atol=1e-12)  # post
    P = rig_final.PENHOLDER22
    grip = np.array([P["post_xy"][0], P["post_xy"][1], P["bore_yz"][1]])
    assert np.allclose(T_h[:3, :3] @ grip + T_h[:3, 3],
                       [GX, 0, D_HAND_TCP], atol=1e-12)
    assert reach == pytest.approx(np.hypot(PEN_LAT_HOLDER - GX,
                                           PEN_EXT_HOLDER), abs=1e-12)
    # the cap is the end the pen leaves by, i.e. IN FRONT of the TCP
    assert (T_c[:3, 3] - np.array([0, 0, D_HAND_TCP])) @ u > 0
    # ...and the numbers Pete has to rule on
    assert np.degrees(P["post_clock"]) == pytest.approx(23.0, abs=0.01)
    # the BORE's own 23 deg — the housing's clocking, which is what puts the
    # square block flush with the blades (2026-09-07, docs/SYSTEM_MODEL.md 7e)
    assert np.degrees(np.arctan2(PEN_LAT_HOLDER - GX, PEN_EXT_HOLDER)) == \
        pytest.approx(23.0, abs=1e-3)   # the constants are 7 dp
    assert np.degrees(P["post_clock"]) == pytest.approx(23.0, abs=1e-4)
    # grip -> the cap's outer face is 30.001 mm, so the graphite past it is
    # 20.0 mm, and since 2026-09-07 that is an INPUT (Pete, off the side
    # view, with the orientation confirmed: "about 2 cm") from which the tip
    # is derived.  It was 53.2 mm while the tip came off the blades, 125.6 at
    # the old 0.110 / 0.110 pair, and 100.5 with the housing end-for-end.
    assert exit_x == pytest.approx(0.030001, abs=1e-6)
    assert (reach - exit_x) == pytest.approx(0.020, abs=1e-6)  # graphite


def test_the_graphite_runs_from_the_cap_to_the_tip(links, joints):
    """`pen_lead` is the one part that is NOT in the CAD (a consumable with an
    adjustable protrusion).  It must start at the CAP'S OUTER FACE — where the
    pen leaves — and end on the planning tip, or the picture and the transform
    disagree.  It started at the housing's TAIL face until 2026-09-03; see
    docs/SYSTEM_MODEL.md 7c.

    AND IT RUNS DOWN THE BORE, NOT DOWN THE TCP -> TIP RAY.  The two parted
    company on 2026-09-04, when the grip moved to the far end of the Fat
    finger plates: both generators used to rebuild this segment from
    `arctan2(pen_lat, pen_ext)`, which would now draw 53 mm of graphite along
    a line 20 deg off the barrel.  `rig_final.penholder22_lead` owns it."""
    GX = rig_final.PENHOLDER22["grip_hand_x"]
    la, lb = rig_final.penholder22_lead(PEN_EXT_HOLDER, PEN_LAT_HOLDER,
                                        D_HAND_TCP)
    tcp_o = np.array([0.0, 0.0, D_HAND_TCP])
    la, lb = la - tcp_o, lb - tcp_o                  # the tcp frame
    nose, reach = float(np.linalg.norm(la)), float(np.linalg.norm(lb))
    u = (lb - la) / np.linalg.norm(lb - la)
    for aid in FLEET_PROPOSED:
        p = f"arm{aid}_"
        lead = links[f"{p}pen_lead"]
        T = _origin_of(lead.find("visual"))          # relative to the tcp
        cyl = lead.find("visual/geometry/cylinder")
        L = float(cyl.get("length"))
        assert L == pytest.approx(np.linalg.norm(lb - la), abs=1e-9)
        axis = T[:3, :3] @ [0, 0, 1]
        assert np.allclose(axis, u, atol=1e-9)
        assert np.allclose(T[:3, 3] - L / 2 * axis, la, atol=1e-9)
        assert np.allclose(T[:3, 3] + L / 2 * axis, lb, atol=1e-9)
        assert float(cyl.get("radius")) == \
            pytest.approx(rig_final.PENHOLDER22["lead_r"], abs=1e-9)
        assert float(lead.find("collision/geometry/cylinder").get("radius")) \
            >= rig_final.PENHOLDER22["lead_r"]


# ==========================================================================
# the static geometry is the study's own
# ==========================================================================
def _box_of(link, kind="collision"):
    e = link.find(kind)
    xyz = np.array([float(v) for v in e.find("origin").get("xyz").split()])
    size = np.array([float(v) for v in e.find("geometry/box").get("size").split()])
    return xyz - size / 2, xyz + size / 2


def test_mount_hardware_matches_the_mounts_module(links):
    for aid, spec in FLEET_PROPOSED.items():
        boxes = mounts.arm_mount_boxes(spec.mount, spec.xy, spec.yaw, H_INV,
                                       tag=f"mount{aid}")
        assert len(boxes) == 2
        for b in boxes:
            lo, hi = _box_of(links[b["name"]])
            assert np.allclose(lo, b["lo"], atol=1e-9), b["name"]
            assert np.allclose(hi, b["hi"], atol=1e-9), b["name"]
        # the boom's VISUAL is the r = boom_r cylinder the box circumscribes
        cyl = links[f"mount{aid}_boom"].find("visual/geometry/cylinder")
        assert float(cyl.get("radius")) == pytest.approx(mounts.MOUNTS.boom_r,
                                                         abs=1e-9)
        lo, hi = _box_of(links[f"mount{aid}_boom"])
        assert float(cyl.get("length")) == pytest.approx(hi[2] - lo[2], abs=1e-9)
        assert hi[2] == pytest.approx(mounts.MOUNTS.ceiling_z, abs=1e-9)
        plo, phi = _box_of(links[f"mount{aid}_plate"])
        assert plo[2] == pytest.approx(H_INV, abs=1e-9)      # ON the flange
        assert phi[2] == pytest.approx(H_INV + mounts.MOUNTS.plate_t, abs=1e-9)


def test_the_ceiling_grid_is_a_level_not_a_structure(links):
    """The grid's steel is not designed and the study gated nothing against
    it.  The URDF may show the LEVEL; it may not claim an obstacle."""
    ceil = links["ceiling_grid_ref"]
    assert ceil.find("visual") is not None
    assert ceil.find("collision") is None
    lo, _ = _box_of(ceil, "visual")
    assert lo[2] == pytest.approx(mounts.MOUNTS.ceiling_z, abs=1e-9)
    # nothing else in the file pretends to be structure
    assert not [n for n in links if n.startswith("frame_")]


def test_paper_is_the_merged_canvas(links):
    W, H = SHEET_FINAL6
    t = rig_final.PAPER_THICK_CM / 100.0
    lo, hi = _box_of(links["paper"])
    assert np.allclose(lo, [0, 0, -t], atol=1e-9)
    assert np.allclose(hi, [W, H, 0.0], atol=1e-9)


def test_environment_is_the_installation_without_the_arms(links):
    env = {lk.get("name") for lk in ET.parse(ENVIRONMENT).getroot()
           .findall("link")}
    static = {n for n in links if not n.startswith("arm")}
    assert env == static
    assert not [j for j in ET.parse(ENVIRONMENT).getroot().findall("joint")
                if j.get("type") != "fixed"]


def test_own_mount_is_collision_filtered_out(root):
    """`mounts.obstacles_for` hands an arm every OTHER arm's hardware and
    never its own.  The URDF says the same — and it says it with the literal
    `drake:` prefix, because drake's parser matches the prefix as a string
    and silently ignores any other one."""
    assert b"xmlns:drake=" in INSTALLATION.read_bytes()
    groups = {g.get("name"): g for g in
              root.findall(f"{DRAKE_NS}collision_filter_group")}
    for aid in FLEET_PROPOSED:
        body = groups[f"arm{aid}_body"]
        ign = [x.get("name") for x in
               body.findall(f"{DRAKE_NS}ignored_collision_filter_group")]
        assert ign == [f"mount{aid}"]
        members = {m.get("link") for m in groups[f"mount{aid}"]
                   .findall(f"{DRAKE_NS}member")}
        assert members == {f"mount{aid}_plate", f"mount{aid}_boom"}
        # ... and only its own
        assert not any(f"mount{other}" in ign for other in FLEET_PROPOSED
                       if other != aid)
